// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkpslCsIHIYXWA30t0W3Zx1RtZr1SiT0',
    appId: '1:371130915379:web:ad995fc56df24e6f382146',
    messagingSenderId: '371130915379',
    projectId: 'play-hub02',
    authDomain: 'play-hub02.firebaseapp.com',
    storageBucket: 'play-hub02.firebasestorage.app',
    measurementId: 'G-DLRCEPF3CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQV3h45Xbx-oEGPJvw874pe6aMY8hN7Io',
    appId: '1:371130915379:android:658084b8df4aab85382146',
    messagingSenderId: '371130915379',
    projectId: 'play-hub02',
    storageBucket: 'play-hub02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5uh_uZksAycNAMdIwGT_BFPxWztcqLHg',
    appId: '1:371130915379:ios:3a81c56b2b2bca4b382146',
    messagingSenderId: '371130915379',
    projectId: 'play-hub02',
    storageBucket: 'play-hub02.firebasestorage.app',
    iosClientId: '371130915379-070v8gqr2iqhkqkjeqgtsmfg8jpcar0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.playHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5uh_uZksAycNAMdIwGT_BFPxWztcqLHg',
    appId: '1:371130915379:ios:3a81c56b2b2bca4b382146',
    messagingSenderId: '371130915379',
    projectId: 'play-hub02',
    storageBucket: 'play-hub02.firebasestorage.app',
    iosClientId: '371130915379-070v8gqr2iqhkqkjeqgtsmfg8jpcar0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.playHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYkpslCsIHIYXWA30t0W3Zx1RtZr1SiT0',
    appId: '1:371130915379:web:755c12bcdb4fae0f382146',
    messagingSenderId: '371130915379',
    projectId: 'play-hub02',
    authDomain: 'play-hub02.firebaseapp.com',
    storageBucket: 'play-hub02.firebasestorage.app',
    measurementId: 'G-6X8L6N1H2B',
  );

}